# Generated by Django 4.1.7 on 2024-03-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_password'),
        ('farmer', '0007_rename_name_farm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('img1', models.CharField(max_length=250)),
                ('img2', models.CharField(max_length=250)),
                ('img3', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('rent', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
