# Generated by Django 4.1.7 on 2024-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quality',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
