# Generated by Django 4.1.7 on 2024-01-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(default='2024-01-29'),
            preserve_default=False,
        ),
    ]
