# Generated by Django 4.1.7 on 2024-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('bit_value', models.CharField(max_length=255)),
                ('bitter', models.CharField(max_length=255)),
            ],
        ),
    ]
