# Generated by Django 4.1.7 on 2024-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
