# Generated by Django 4.1.7 on 2024-02-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profilepic'),
        ('dealer', '0003_bit_bitter_address_bit_farmer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
